---
all:
  children:
    docker_servers:
      hosts:
        svlazdock1:
          ansible_host: svlazdock1
          ansible_user: ansible
          ansible_become: true
        svlazdev1:
          ansible_host: svlazdev1
          ansible_user: ansible
          ansible_become: true
