---
all:
  children:
    application_servers:
      hosts:
        svlazdock1:
          ansible_host: svlazdock1
          ansible_user: ansible
          ansible_become: true
    development_servers:
      hosts:
        svlazdev1:
          ansible_host: svlazdev1
          ansible_user: ansible
          ansible_become: true
    dmz_servers:
      hosts: {}
