---
all:
  children:
    docker_servers:
      hosts:
        SVLAZDOCK1:
          ansible_host: svlazdock1.local
          ansible_user: ansible
          ansible_become: true
          server_features:
            - docker
            - ufw
            - chezmoi
            - traefik
            - ansible_pull_setup
