---
all:
  children:
    docker_servers:
      hosts:
        svlazdock1:
          ansible_host: svlazdock1
          ansible_user: ansible
          ansible_become: true
          server_features:
            - system_setup
            - docker
            - ufw
            - chezmoi
            - ansible_pull_setup
            - maintenance
          compose_modules:
            - traefik
          docker_users:
            - ansible
            - jean-paul
        svlazdev1:
          ansible_host: svlazdev1
          ansible_user: ansible
          ansible_become: true
          server_features:
            - system_setup
            - docker
            - ufw
            - chezmoi
            - ansible_pull_setup
            - maintenance
          compose_modules: []
          docker_users:
            - ansible
            - jean-paul
