---
# Traefik role - Deploy Traefik as a Docker container
dependencies:
  - geerlingguy.docker

galaxy_info:
  author: DevSecNinja
  description: Deploy Traefik reverse proxy as a Docker container
  company: DevSecNinja
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - trixie
    - name: Ubuntu
      versions:
        - noble
