---
# UFW Firewall role
dependencies: []

galaxy_info:
  author: DevSecNinja
  description: Configure UFW firewall
  company: DevSecNinja
  license: MIT
  min_ansible_version: "2.20"
  platforms:
    - name: Debian
      versions:
        - trixie
    - name: Ubuntu
      versions:
        - noble
