---
# Ansible Pull Setup role
dependencies: []

galaxy_info:
  author: DevSecNinja
  description: Automate ansible-pull with cron or systemd
  company: DevSecNinja
  license: MIT
  min_ansible_version: "2.20"
  platforms:
    - name: Debian
      versions:
        - trixie
    - name: Ubuntu
      versions:
        - noble
