---
# External roles from Ansible Galaxy
roles:
  - name: geerlingguy.docker
    version: 8.0.0

collections:
  - name: community.general
    version: ">=9.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
