---
# External roles from Ansible Galaxy
roles:
  - name: geerlingguy.docker
    version: 7.4.1

collections:
  - name: community.general
    version: "==12.3.0"
  - name: community.docker
    version: "==5.0.6"
  - name: ansible.posix
    version: "==2.1.0"
