---
# Docker Compose Modules role
dependencies:
  - geerlingguy.docker

galaxy_info:
  author: DevSecNinja
  description: Deploy Docker Compose modules
  company: DevSecNinja
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - trixie
    - name: Ubuntu
      versions:
        - focal
